### ISSUE TITLE
Is this repo still "read-only"?

### ISSUE THREAD

**Issue by aallan** [raspberrypi/pico-tflmicro#9]
With the lack of support from upstream is this effectively the place where the RP2040 port of TFLite "lives" now?

If so we should get some nightlies going and expand the README and other getting-started instructions and associated [documentation](https://github.com/raspberrypi/documentation/issues/3085). 

Looks like @kilograham has [a commit](https://github.com/raspberrypi/pico-tflmicro/compare/main...graham) from back in 2020 that we should probably merge in I guess? Graham, what was that about, do you remember at all?

**Comment by kilograham** [comment]
yeah you should probably merge that if it works - we use INTERFACE libraries vs STATIC ones with SDK

**Comment by aallan** [comment]
Ping @petewarden.

**Comment by aallan** [comment]
Based on #12, I'm now calling this repo "as upstream as it gets" for the RP2 port. This is the place where the RP2040 port of TFLite "lives" now!
